spring:
  application:
    name: todo

# H2 Database
  datasource:
    url: jdbc:h2:mem:todo
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always

# JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

